name: trident
dependencies:
- cairo=1.12.18=6
- cycler=0.10.0=py27_0
- fontconfig=2.11.1=5
- freetype=2.5.5=0
- h5py=2.6.0=np111py27_1
- hdf5=1.8.16=0
- libpng=1.6.17=0
- libxml2=2.9.2=0
- matplotlib=1.5.1=np111py27_0
- mkl=11.3.3=0
- mpmath=0.19=py27_0
- numpy=1.11.0=py27_1
- openssl=1.0.2h=0
- pip=8.1.1=py27_1
- pixman=0.32.6=0
- pycairo=1.10.0=py27_0
- pyparsing=2.1.1=py27_0
- pyqt=4.11.4=py27_1
- python=2.7.11=0
- python-dateutil=2.5.3=py27_0
- pytz=2016.4=py27_0
- qt=4.8.7=1
- readline=6.2=2
- setuptools=20.7.0=py27_0
- sip=4.16.9=py27_0
- six=1.10.0=py27_0
- sqlite=3.9.2=0
- sympy=1.0=py27_0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- yt=3.2.3=py27_0
- zlib=1.2.8=0
- pip:
  - trident==0.5.1
